# nome que vai aparecer no github
name: 'Execucao manual'
# triggers ou gatilhos de execucao
# gatilho de exec manual = workflow_diospatch
on:
  workflow_dispatch:

jobs:
  # - baixar as dependencias
  # - compilar
  # - testar
  e2e-tests:
    # maquina que vai rodar
    runs-on: ['ubuntu-latest']

    #passo a paso das acoes do job
    steps:
      # - run: echo 'Execucao manual'
      - uses: actions/checkout@v4
      # - uses: actions/setup-node@v4
      #     with:
      #         node-version: lts/*
      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependências
        run: yarn

      - name: Instalando Playwright
        run: yarn playwright install --with-deps

      - name: Testes E2E (end-to-end)
        run: yarn run e2e

      - uses: actions/upload-artifact@v4
        # por padrao a pipeline cancela se houver erro para evitar que ele cancele o passo seguinte no caso de erro, se quiser que a pipeline continue, basta adicionar o parametro 'if: ${{ !cancelled() }}'
        if: ${{ !cancelled() }}
        with:
          name: relatorio-de-testes
          path: ./playwright-report



# comit:
# git add <arquivos> - adicionar as alterações para a area de 'staging'
# git commit -m "mensagem do commit"
# git push 
# convenção de comits (conventional comits) = comentários (ex: ci, feat, fix, test)         